### ISSUE TITLE
How to show the value in Pie chart

### ISSUE THREAD

**Issue by esrevinu** [cyberpython/AwesomeChartJS#4]
As title says.
In addition,when all values equal zero there exists an ugly appearence which can be improved more or less

**Comment by cyberpython** [comment]
As the code is right now, it just displays the label's text. You could replace that with or append to it the value for each part of the pie - please keep in mind that you would have to build an array of the text you wish to display prior to any calculations and use that in place of the `labels` array, since the width of the labels is used to determine the pie's radius.
